use ratatui::style::Color;

#[derive(Clone, Debug)]
pub struct Theme {
    pub name: &'static str,
    pub desc: &'static str,
    pub primary: Color,
    pub accent: Color,
    pub dim: Color,
    pub bg: Color,
    pub surface: Color,
    pub border: Color,
    pub success: Color,
    pub error: Color,
}

pub const THEMES: &[Theme] = &[
    Theme {
        name: "Midnight",
        desc: "Deep dark with electric cyan glow",
        primary: Color::Cyan,
        accent: Color::Magenta,
        dim: Color::DarkGray,
        bg: Color::Rgb(10, 10, 20),
        surface: Color::Rgb(20, 20, 35),
        border: Color::Rgb(99, 102, 241),
        success: Color::Green,
        error: Color::Red,
    },
    Theme {
        name: "Matrix",
        desc: "Classic hacker green on black",
        primary: Color::Green,
        accent: Color::Rgb(0, 255, 65),
        dim: Color::DarkGray,
        bg: Color::Rgb(0, 5, 0),
        surface: Color::Rgb(5, 15, 5),
        border: Color::Green,
        success: Color::Green,
        error: Color::Red,
    },
    Theme {
        name: "Dracula",
        desc: "Purple/pink dark fantasy",
        primary: Color::Magenta,
        accent: Color::Rgb(139, 233, 253),
        dim: Color::DarkGray,
        bg: Color::Rgb(20, 15, 25),
        surface: Color::Rgb(30, 22, 40),
        border: Color::Rgb(189, 147, 249),
        success: Color::Green,
        error: Color::Red,
    },
    Theme {
        name: "NeonPunk",
        desc: "Cyberpunk neon on black",
        primary: Color::Rgb(255, 0, 255),
        accent: Color::Rgb(255, 255, 0),
        dim: Color::DarkGray,
        bg: Color::Rgb(10, 0, 15),
        surface: Color::Rgb(20, 5, 30),
        border: Color::Rgb(255, 0, 255),
        success: Color::Green,
        error: Color::Red,
    },
    Theme {
        name: "Ocean",
        desc: "Deep ocean electric blue",
        primary: Color::Rgb(100, 180, 255),
        accent: Color::Cyan,
        dim: Color::DarkGray,
        bg: Color::Rgb(5, 10, 25),
        surface: Color::Rgb(10, 20, 40),
        border: Color::Rgb(50, 150, 255),
        success: Color::Green,
        error: Color::Red,
    },
    Theme {
        name: "Sunset",
        desc: "Warm sunset orange and red",
        primary: Color::Yellow,
        accent: Color::Red,
        dim: Color::DarkGray,
        bg: Color::Rgb(20, 10, 5),
        surface: Color::Rgb(30, 18, 10),
        border: Color::Rgb(255, 100, 0),
        success: Color::Green,
        error: Color::Red,
    },
    Theme {
        name: "Arctic",
        desc: "Cold crisp arctic blue",
        primary: Color::Rgb(150, 200, 255),
        accent: Color::White,
        dim: Color::DarkGray,
        bg: Color::Rgb(5, 10, 20),
        surface: Color::Rgb(12, 20, 35),
        border: Color::Rgb(200, 220, 255),
        success: Color::Green,
        error: Color::Red,
    },
    Theme {
        name: "Monokai",
        desc: "Classic code-editor Monokai",
        primary: Color::Rgb(230, 219, 116),
        accent: Color::Rgb(166, 226, 46),
        dim: Color::DarkGray,
        bg: Color::Rgb(20, 20, 15),
        surface: Color::Rgb(30, 28, 22),
        border: Color::Rgb(230, 219, 116),
        success: Color::Green,
        error: Color::Red,
    },
    Theme {
        name: "Crimson",
        desc: "Deep red dark theme",
        primary: Color::Red,
        accent: Color::Rgb(255, 100, 100),
        dim: Color::DarkGray,
        bg: Color::Rgb(15, 5, 5),
        surface: Color::Rgb(25, 12, 12),
        border: Color::Rgb(200, 50, 50),
        success: Color::Green,
        error: Color::Red,
    },
    Theme {
        name: "Nord",
        desc: "Nordic dark blue",
        primary: Color::Rgb(100, 150, 220),
        accent: Color::Rgb(139, 233, 253),
        dim: Color::DarkGray,
        bg: Color::Rgb(10, 14, 22),
        surface: Color::Rgb(18, 24, 36),
        border: Color::Rgb(100, 150, 220),
        success: Color::Green,
        error: Color::Red,
    },
];

pub fn get_theme(idx: usize) -> &'static Theme {
    &THEMES[idx.min(THEMES.len() - 1)]
}
